version: '2.0'
services:

  seafile_db:
    image: mariadb:10.4.12-bionic
    container_name: seafile_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PW}
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - seafile-net

  seafile_memcached:
    image: memcached:1.5.22-alpine
    container_name: seafile_memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile_elasticsearch:
    image: seafileltd/elasticsearch-with-ik:5.6.16
    container_name: seafile_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - seafile-net

  seafile_server:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:7.0.10
    container_name: seafile_server
    expose:
      - ${PORT}
    volumes:
      - ./data/seafile-data:/shared
      - ./seafile.nginx.conf.template:/templates/seafile.nginx.conf.template:ro
    environment:
      - DB_HOST=seafile_db
      - DB_ROOT_PASSWD=${DB_PW}
      - SEAFILE_ADMIN_EMAIL=${ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${ADMIN_PW}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=${DOMAIN}
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=${PORT}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
    depends_on:
      - seafile_db
      - seafile_memcached
      - seafile_elasticsearch
    networks:
      - seafile-net
      - reverse-proxy

networks:
  seafile-net:
  reverse-proxy:
    external:
      name: ${REVERSE_PROXY_NET}