version: '2.0'
services:

  seafile_db:
    image: mariadb:10.4.12-bionic
    container_name: seafile_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PW}  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${SEAFILE_PATH}/data/mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  seafile_memcached:
    image: memcached:1.5.22-alpine
    container_name: seafile_memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile_elasticsearch:
    image: seafileltd/elasticsearch-with-ik:5.6.16
    container_name: seafile_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ${SEAFILE_PATH}/data/elasticsearch/data:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile-net

  seafile_server:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile_server
    expose:
      - ${PORT}
    volumes:
      - ${SEAFILE_PATH}/data/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=${DB_HOST}
      - DB_ROOT_PASSWD=${DB_PW}
      - SEAFILE_ADMIN_EMAIL=${ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${ADMIN_PW}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=${PORT}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
    depends_on:
      - seafile_db
      - seafile_memcached
      - seafile_elasticsearch
    networks:
      - seafile-net

networks:
  seafile-net: